language: android

jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-15
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
        
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
    
    # Additional components
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services

  licenses:
    - 'android-sdk-license-.+'

before_install:
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - echo "bintray.apikey=fake_key" >> local.properties
  - echo "bintray.user=fake_user" >> local.properties

script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)