language: android

jdk: oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
        
    - sys-img-armeabi-v7a-android-25
    
    # Additional components
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services

  licenses:
    - 'android-sdk-license-.+'

before_install:
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - echo "bintray.apikey=fake_key" >> local.properties
  - echo "bintray.user=fake_user" >> local.properties

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - ./gradlew assembleDebug